#######################################################
# 
# Ogloszenie_python.py
# Python implementation of the Class Ogloszenie
# Generated by Enterprise Architect
# Created on:      24-cze-2024 16:23:11
# Original author: Wiktor
# 
#######################################################


class Ogloszenie:
    def dodaj(garazOgloszenie):
        pass

    def modyfikuj(garazOglosznie):
        pass

    def pobierz():
        pass

    def pobierz(garazOgloszenie):
        pass

    def wyliczOgloszenieRefresh():
        pass

    def zmienStatusNajmu(garazOgloszenie):
        pass