///////////////////////////////////////////////////////////
//  Ogloszenie_cs.cs
//  Implementation of the Class Ogloszenie
//  Generated by Enterprise Architect
//  Created on:      24-cze-2024 16:23:44
//  Original author: Wiktor
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Struktura {
	public class Ogloszenie {

		private double cenaNajmu;
		/// <summary>
		/// Czas rozpoczêcia og³oszenia
		/// </summary>
		private LocalTime dataStart;
		/// <summary>
		/// Czas wygasniecia co miesiac, aby zwolnic miejsce na serwerach.
		/// </summary>
		private LocalTime dataStop;
		private String nazwa;
		/// <summary>
		/// Powinnosc refreshowania ogloszenia, w celu aktualizacji ze jest to obiekt
		/// czynny. W przeciwnym wypadku jesli bedzie falsz , nastapi usuniecie ogloszenie.
		/// Co da nam zwolnienie miejsca na serwerze.
		/// </summary>
		private boolean ogloszenieRefresh;
		private String opis;
		/// <summary>
		/// Czy jest obiekt aktualnie wynajmowany czy nie.
		/// </summary>
		private StatusNajmu status;
		private String[0...10] URLZdjec;

		public Ogloszenie(){

		}

		~Ogloszenie(){

		}

		/// 
		/// <param name="garazOgloszenie"></param>
		public void dodaj(Ogloszenie garazOgloszenie){

		}

		/// 
		/// <param name="garazOglosznie"></param>
		public void modyfikuj(Ogloszenie garazOglosznie){

		}

		public List<Ogloszenie> pobierz(){

			return null;
		}

		/// 
		/// <param name="garazOgloszenie"></param>
		public void pobierz(int, StatusNajmu garazOgloszenie){

		}

		public int wyliczOgloszenieRefresh(){

			return 0;
		}

		/// 
		/// <param name="garazOgloszenie"></param>
		public void zmienStatusNajmu(StatusNajmu garazOgloszenie){

		}

	}//end Ogloszenie

}//end namespace Struktura